from __future__ import annotations

import json
import re
from datetime import datetime
from pathlib import Path
from typing import Any

STORAGE_DIR = Path.home() / "qagent-data" / "presentations"


def _ensure_dir() -> Path:
    STORAGE_DIR.mkdir(parents=True, exist_ok=True)
    return STORAGE_DIR


def _timestamp() -> str:
    return datetime.now().strftime("%Y%m%d-%H%M%S")


def _slugify(text: str) -> str:
    text = text.strip().lower()
    text = re.sub(r"[^a-z0-9]+", "-", text)
    text = text.strip("-")
    return text or "untitled"


def _normalize_slide(slide: Any) -> dict[str, Any]:
    if not isinstance(slide, dict):
        return {"title": str(slide), "bullets": []}
    title = str(slide.get("title", "")).strip() or "Untitled"
    bullets = slide.get("bullets")
    if bullets is None:
        content = slide.get("content")
        if isinstance(content, str) and content.strip():
            bullets = [line.strip() for line in content.splitlines() if line.strip()]
        else:
            bullets = []
    if isinstance(bullets, str):
        bullets = [bullets]
    if not isinstance(bullets, list):
        bullets = [str(bullets)]
    bullets = [str(b) for b in bullets]
    return {"title": title, "bullets": bullets}


def _normalize_slides(slides: Any) -> list[dict[str, Any]]:
    if slides is None:
        return []
    if isinstance(slides, str):
        try:
            slides = json.loads(slides)
        except json.JSONDecodeError:
            return [{"title": slides, "bullets": []}]
    if isinstance(slides, dict):
        slides = [slides]
    if not isinstance(slides, list):
        return []
    return [_normalize_slide(s) for s in slides]


def make_markdown_deck(title: str, slides: list[dict]) -> str:
    try:
        normalized = _normalize_slides(slides)
        directory = _ensure_dir()
        safe_title = title.strip() or "Untitled"
        filename = f"{_timestamp()}-{_slugify(safe_title)}.md"
        path = directory / filename

        lines: list[str] = []
        lines.append("---")
        lines.append("marp: true")
        lines.append("---")
        lines.append("")
        lines.append(f"# {safe_title}")
        lines.append("")

        for slide in normalized:
            lines.append("---")
            lines.append("")
            lines.append(f"## {slide['title']}")
            lines.append("")
            for bullet in slide["bullets"]:
                lines.append(f"- {bullet}")
            if slide["bullets"]:
                lines.append("")

        path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
        return f"Saved presentation (markdown) to {path}"
    except Exception as exc:
        return f"Error: failed to write markdown deck: {exc}"


def make_pptx(title: str, slides: list[dict]) -> str:
    try:
        from pptx import Presentation
    except ImportError:
        return "Error: python-pptx is not installed. Run: pip install python-pptx"

    try:
        normalized = _normalize_slides(slides)
        directory = _ensure_dir()
        safe_title = title.strip() or "Untitled"
        filename = f"{_timestamp()}-{_slugify(safe_title)}.pptx"
        path = directory / filename

        prs = Presentation()

        title_layout = prs.slide_layouts[0]
        title_slide = prs.slides.add_slide(title_layout)
        if title_slide.shapes.title is not None:
            title_slide.shapes.title.text = safe_title
        for placeholder in title_slide.placeholders:
            if placeholder.placeholder_format.idx == 1:
                placeholder.text = "Generated by qagent"
                break

        content_layout = prs.slide_layouts[1]
        for slide_data in normalized:
            slide = prs.slides.add_slide(content_layout)
            if slide.shapes.title is not None:
                slide.shapes.title.text = slide_data["title"]
            body = None
            for placeholder in slide.placeholders:
                if placeholder.placeholder_format.idx == 1:
                    body = placeholder
                    break
            if body is not None and slide_data["bullets"]:
                tf = body.text_frame
                tf.text = slide_data["bullets"][0]
                for bullet in slide_data["bullets"][1:]:
                    p = tf.add_paragraph()
                    p.text = bullet

        prs.save(str(path))
        return f"Saved presentation (pptx) to {path}"
    except Exception as exc:
        return f"Error: failed to write pptx: {exc}"


def list_presentations() -> str:
    try:
        directory = _ensure_dir()
        files = [p for p in directory.iterdir() if p.is_file()]
        files.sort(key=lambda p: p.stat().st_mtime, reverse=True)
        if not files:
            return "No presentations saved yet."
        return "\n".join(str(p) for p in files)
    except Exception as exc:
        return f"Error: failed to list presentations: {exc}"


SCHEMAS: dict[str, dict[str, Any]] = {
    "make_markdown_deck": {
        "name": "make_markdown_deck",
        "description": (
            "Build a Markdown slide deck (Marp/Reveal style with '---' separators) "
            "and save it under ~/qagent-data/presentations/."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "title": {"type": "string", "description": "Deck title (first slide)."},
                "slides": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "title": {"type": "string"},
                            "bullets": {
                                "type": "array",
                                "items": {"type": "string"},
                            },
                        },
                        "required": ["title"],
                    },
                },
            },
            "required": ["title", "slides"],
        },
    },
    "make_pptx": {
        "name": "make_pptx",
        "description": (
            "Build a PowerPoint (.pptx) deck via python-pptx and save it under "
            "~/qagent-data/presentations/. Requires python-pptx."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "title": {"type": "string", "description": "Deck title (first slide)."},
                "slides": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "title": {"type": "string"},
                            "bullets": {
                                "type": "array",
                                "items": {"type": "string"},
                            },
                        },
                        "required": ["title"],
                    },
                },
            },
            "required": ["title", "slides"],
        },
    },
    "list_presentations": {
        "name": "list_presentations",
        "description": "List saved presentation files (newest first).",
        "parameters": {"type": "object", "properties": {}},
    },
}


def dispatch(name: str, args: dict[str, Any]) -> str | None:
    if not isinstance(args, dict):
        args = {}

    if name == "make_markdown_deck":
        title = str(args.get("title", "") or "")
        slides = _normalize_slides(args.get("slides"))
        return make_markdown_deck(title, slides)

    if name == "make_pptx":
        title = str(args.get("title", "") or "")
        slides = _normalize_slides(args.get("slides"))
        return make_pptx(title, slides)

    if name == "list_presentations":
        return list_presentations()

    return None
